### ISSUE TITLE
please make an permission explenation....

### ISSUE THREAD

**Issue by Blazzycrafter** [irsat000/CAI-Tools#13]
like:
why dow we need read browser history:
![image](https://github.com/irsat000/CAI-Tools/assets/39300111/f66cfd74-f83b-4738-9747-709d00686047)
or why do we need acess to google:
![image](https://github.com/irsat000/CAI-Tools/assets/39300111/af5a2233-f384-47ab-9f15-5daa94eb2718)

do an open issue ore something an pin it....

**Comment by Drflash55** [comment]
Also questioning this as well, as it's very suspicious that it's requiring these.

**Comment by ArakiSatoshi** [comment]
Chrome disabled this extension due to this permission on my side. I'm using the version that is available on Chrome Web Store.

**Comment by srsutherland** [comment]
The google permission is from 0e45b3a3cd9672b3296686f80fe5ea26876f5e94 "Adding BrainyPDF ad on google"

From the developer:

```
<div class="ad-explanation">
  <h4>Why am I seeing this?</h4>
    <p>As the developer of CAI Tools, I would like to keep the extension free and up to date. Sponsorship helps. For reports and suggestions, <a href="https://www.github.com/irsat000/CAI-Tools/issues" target="_blank">CAI-Tools issues</a></p>
    <a class="close-cai-ad">Close Ad</a>
</div>
```

**Comment by irsat000** [comment]
Sorry, I haven't seen the Issue until now. Yes, I was thinking about adding this ad, but gave up on the idea. The codes were kept in the source code, I forgot to delete the permission from the Manifest file.

New update is currently being reviewed. It will be gone with it. In the new update, you should be able to download both Chat1 and chat2 history together. Previously it was only possible to download whatever the character was. This is good for those who had conversations with the altered characters.

**Comment by Blazzycrafter** [comment]
@irsat000 
but seriusly XD
you should add somthing that explains why you use certian permission like 
my browser history with my p0rn collection XC
(*yes i dont use incognito dont jugeme XD*)

**Comment by irsat000** [comment]
Are you referring to webNavigation permission? That's how I know you are inside chat or history page of character.ai. So I can create the button and toolbox inside there.

**Comment by irsat000** [comment]
@Blazzycrafter Normally, I wouldn't need the webNavigation permission because content.js would run at every new page. But character.ai is a Single Page Application (SPA), which means once content.js is loaded, it will never reload again until you refresh or leave the website. Because technically you never leave the one and only page that is SPA, only the URL and content change. 

That means I need to check which page the user is in in an infinite loop with interval command or simply get navigation permission. I chose the latter because it's a lot more efficient.

**Comment by irsat000** [comment]
I tried MutationObserver, it had problems, or I couldn't make it work I don't remember which one. If it's going to remove our problems, I can try it again sometime, maybe this week.

**Comment by irsat000** [comment]
@srsutherland Oh my, that is 10 times faster, no jamming, no problems and no need for permission. It took 10 minutes to implement. Apparently I couldn't make it work, probably couldn't figured it out how to initialize it at first load. Me from 9 months ago was quite bad huh.

Thanks for the advice, I already tested it and made a commit. you should see it on store soon.
