### ISSUE TITLE
Issue when exporting C.ai chats and importing into Tavern.ai

### ISSUE THREAD

**Issue by Astral0Trinity** [irsat000/CAI-Tools#15]
Basically exactly as the title says, recently have had troubles when exporting a C.ai chat log, using C.ai tools, as a jsonl file. When I import it into Tavern.ai it just makes the import window go blank. Haven't had this problem with older chats.

**Comment by irsat000** [comment]
Could you upload problematic jsonl file here?

**Comment by irsat000** [comment]
Is it fixed by itself?

**Comment by Astral0Trinity** [comment]
To be honest, I just circumvented the problem of fixing the chat exporting
by just copy pasting the replies and messages. And also because I didn't
want to send the chats I had.

**Comment by irsat000** [comment]
Oobabooga also has problems. Are you sure you are using Tavern UI? You don't see TextGen Web UI or something right?

Also you can give me a new chat, doesn't need to be super secret stuff. It's crucial that for me to fix this issue. I can't do it without it because I don't use Tavern.

**Comment by Astral0Trinity** [comment]
Yeah I'm using TavernAI UI. I'll start a new chat and try and export-import
it to see if it works. If it works proeprly, I'Il let you know. If it
doesn't I have some idea of what could be the issue but I'll have to see.

**Comment by irsat000** [comment]
If there is a change in JSONL format, I need to update mine. That's why I need a JSONL example.

But there might be a temporary problem with the UI aswell. Maybe for only yours.

**Comment by Astral0Trinity** [comment]
Okay, I tried replicating the issue but for some reason it only happens
with like 2 or 3 of my already exported chats. The other chats I have and
ones I just made and exported, import just fine

**Comment by irsat000** [comment]
This is not really helpful. You are trying to debug all by yourself.

Exports means C.AI exports, correct? I don't need them, I already know what they are like. I am asking for Tavern exports, create new ones. 5-10 message long is fine.

**Comment by Astral0Trinity** [comment]
Yeah sorry, I'm just trying to see why it's like that. I'll make one and
send it.

**Comment by Astral0Trinity** [comment]
Also yeah, I'm talking about exports from C.AI not from Tavern. THe
problem I had was when I exported a chat from C.AI and tried to import it
into Tavern where I had the issue.

**Comment by irsat000** [comment]
Are you still here?

**Comment by irsat000** [comment]
Send it already lol
