### ISSUE TITLE
Issue when exporting CAI chat to oobabooga

### ISSUE THREAD

**Issue by AkMesitochito** [irsat000/CAI-Tools#16]
Hello, when i download the CAI as json for the oobabooga chat it download a version that the application cant read. The version that i download is all the text one behind the other, unlike the chat history that the app saves that is ordenated in other way. How do i solve this? thanks

![image](https://github.com/irsat000/CAI-Tools/assets/127821380/3140ce01-6f0e-4b4e-bfaf-d09d7bef65c1)

the one in the bottom up is the version that download from CAI and the one in the downside is how the chat history should look like to be readed by the app

**Comment by irsat000** [comment]
Indentation has no effect, it seems the keys are updated. "data" and "data_visible" are identical keys that hold an array of arrays, these nested arrays hold message pairs, one from the user and one from the character.

I am not following the changes much, it seems Oobabooga changed the format a bit. Not much, "internal" replaced "data" and "visible" replaced "data_visible" key. Aside from that, I there is only one other change, the initialization of the chat. Oobabooga allowed users to write first then the character would reply with its first ever message. Is this still the case or did they change it?

I can fix this easily, just let me know if there are multiple versions of Oobabooga or this is the new update. Providing multiple of your new chats would help too.

I am currently working on an offline CAI library kind of thing, I will update the extension alongside it.

**Comment by irsat000** [comment]
Could you try b895f8b and let me know if Oobabooga is fixed? Also check out the new Read Offline design.

chrome://extensions/ go here, open developer mode and click on Load Unpacked and choose the extension folder. It will detect the manifest file automatically and install the extension.

I really wouldn't ask you this if I knew how to use Oobabooga haha. I appreciate it, thanks.

**Comment by irsat000** [comment]
Could you upload the Oobabooga file and the one you downloaded using new version of cai tools?

**Comment by irsat000** [comment]
Which colab link are you using?

**Comment by irsat000** [comment]
Try this one 2b0345a

**Comment by AkMesitochito** [comment]
hello, im so sorry that i couldnt answer you, now it works perfectly, thank you so so so much for your time and efforts, you saved me rewrite my chats manually xD thank you again

**Comment by irsat000** [comment]
I am keeping this open for the upcoming version waiting for review. Let me know if it works after that too.

By the way, which one works now, old version on chrome or the one I just gave?

**Comment by AkMesitochito** [comment]
The last one you gave me, thats the one

**Comment by AkMesitochito** [comment]
sups
i downloaded the last vbersion and the downloadable character and the chats still works perfectly
