### ISSUE TITLE
Download character not working anymore

### ISSUE THREAD

**Issue by Propialis** [irsat000/CAI-Tools#17]
Updated the extension, now nothing happens when i click on download character as json/png or even when i click on show settings.

This is what appears in the console:
![image](https://github.com/irsat000/CAI-Tools/assets/56273117/65fa7911-dd5d-4b9d-b477-9612c57d71c8)

**Comment by irsat000** [comment]
You need to login to see the character information right now. If there is anything I can do with Guest method, I will do it.

**Comment by irsat000** [comment]
New version should work fine, have you tried it?

**Comment by Propialis** [comment]
Yes! Works now, awesome, thank you so much for the fast action :)
