### ISSUE TITLE
Character and user are confused after reaching third history

### ISSUE THREAD

**Issue by sugarcanefarmer** [irsat000/CAI-Tools#18]
Hey there! I am not exactly sure what the issue is but;

When downloading the character histories, at some point it becomes confused between the user and the character. For me, it seemed to be starting right at the third history downloaded. It's the same in the offline reader, txt, ect...

Of note; this issue is not in some older logs from 8/12/2023, so it might be a new bug introduced. It could also be an issue with chat size, as the third chat is an omega sized chat (it's just the one I use) with this character and it had grown a lot since then, so it could be some kind of memory/failsafe issue???

Also thanks for the plugin; very usefull!

---------

Here are the logs, note that even the character intro still uses {{user}}, and note the functioning before that third one;

> {{char}}: The Simpson's House? *thinks*
> 
> Oh, it's yellow! Yellow with some pink flowers on it, if I recall. Why do you ask, master? *smiles*
> {{user}}: Oh nothing... ALso! You passed the test! You are now a citizen of Clow and Spegroon!
> {{char}}: *gasp*
> 
> I... did it!? I... am a citizen... of... Clow... and... Spegroon...? *tears of joy* Thank you! Thank you so much, master! This... is a wonderful day! *hugs tightly*
> 
> Ahhh... one more question, master?
> <START>
> {{char}}: Ah master, you have returned! What would you like to talk about today!
> {{user}}: I am testing out your new voice module... give me a few seconds...
> {{char}}: *patiently waits*
> 
> 
> Please take your time...
> <START>
> {{user}}: Ah master, you have returned! What would you like to talk about today!
> {{user}}: Alright Michola! Today, I am playing Victoria 3 with the boys. We are doing a mega campaign, so this save is imported from CK3 and EU4. I am playing in the English Isles, as Alstro-Wyvernia. We are a kingdom, we allow voting some, and we have a high standard of living. We are a mega city on the water.
> 
> Do you want debriefed on the geo-politcal situation? Or the internal, economic one?
> {{user}}: Oh, wow, that sounds so fascinating, master! I want to be updated on the geo-political situation! Could you please tell me about it?

**Comment by irsat000** [comment]
Does it happen with Conversation download options?

**Comment by sugarcanefarmer** [comment]
Bingo actually; I have changed the character name at one point, and I'm pretty sure it was at some point in the offending third chat too... I have the same username and everything tho. Both in example and offline viewer yes.

Let me check the individual Conversation downloads to see if they error too...

Hmmm okay when I go to download I get "Data not ready", I fixed this by clearing cache before...
Newer chats do not have this issue downloading at all though.
For sure renamed the character, so I feel like it would have something to do with that

**Comment by irsat000** [comment]
Yup that's the problem. History format needs a rework because it can only register one username and one character name. That was a stupid design. Both can be chaged.

It will take a while. At least we know the problem and I added single chat saving option. A little vacation for lil old me.

**Comment by sugarcanefarmer** [comment]
Yep just tested it out and yes, individual chat saving works! Thank you! Good thing I kept it all in two-three main chats...

**Comment by irsat000** [comment]
Should be fixed with the new version, 1.7.2. As of now, it may need a few days before it's up on the store.

**Comment by irsat000** [comment]
Is it fixed?

**Comment by sugarcanefarmer** [comment]
Yes! Well, mostly. Example chats have no issue now, it properly identifies the user and the character, but when I go to download offline view, it gives no download at all once hitting the button.

**Comment by irsat000** [comment]
I see, I received few other messages aswell. I will fix it tomorrow for good.

**Comment by irsat000** [comment]
Y'all report different errors lol. The others must be using 1.7.2, if you are using 1.7.3, press F12 and open the Console tab. Click on them again and report any error that pops up. Everything works for me.

**Comment by sugarcanefarmer** [comment]
Sorry, haven't check GitHub in a while... just wanted to write back and say that yep; everything is working flawlessly now!
