### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by Chicbellab** [irsat000/CAI-Tools#19]
Not downloading Oobabooga chat or Tavern Chat, When clicking on them it just sits there and does nothing.

**Comment by Chicbellab** [comment]
Can download Character json/png and show settings but to download the chat is a no go. Can read offline though

**Comment by irsat000** [comment]
Sorry, that's completely me not testing properly haha. I removed a line of code that some other code needed, that's the problem. I fixed it, we will wait for google to approve. Let me know when it's working.

**Comment by Chicbellab** [comment]
Hmm.. Still nothing, its just the download tavern and Ob. chat thats not working.

**Comment by Corvus001** [comment]
Hey, no se descarga la opcion "ejemplo de chat/ definicion" :(

**Comment by Corvus001** [comment]
Hey, the "chat example/definition" option is not downloading :(

**Comment by irsat000** [comment]
New version is not approved yet, relax.

**Comment by Chicbellab** [comment]
ahh kay thanks..

**Comment by irsat000** [comment]
Should be working now.
