### ISSUE TITLE
Character card downloader

### ISSUE THREAD

**Issue by memmam** [irsat000/CAI-Tools#2]
Can CAI Tools be updated to add a direct character card downloader when you're on the `https://beta.character.ai/editing?char=` page, like the old CharacterAI Dumper script used to? As it is, I need to make a cai-dump, load that into AI Character Editor, and then manually add the Example Chats, which is a lot of extra work for what could be a one-button process.

Preferably, I'd like it to give the user the option of either a JSON file, or a .PNG character card for e.g. Tavern auto-importing the character avatar along with the personality data.

Thank you! <3

**Comment by irsat000** [comment]
I have something like this in mind. Will be ready soon.

**Comment by irsat000** [comment]
Previous update was json character. Now included the character card downloader. Have fun!
