### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by MichaelHinrichs** [irsat000/CAI-Tools#20]
There are some features that don't work in rooms.

- Download Character (json)
- Download Character Card (png)
- Show settings

If an attempt is made to use these, an error says "Couldn't find logged in user or character id."
This may be fixed by allowing the user to select which character they want to download.

**Comment by irsat000** [comment]
Only issue here is that the button shows up in the rooms. I thought I removed that haha.

Nevermind, I will just work on it and add features for the rooms. Character stuff + Offline chat download should be sufficient. Probably will take couple of weeks, I am working on a new website right now.
