### ISSUE TITLE
Userscript?

### ISSUE THREAD

**Issue by Nessuno2000** [irsat000/CAI-Tools#21]
Is there a userscript for this extension? If there is one, it may be compatible with iOS through the userscripts safari extension app.

**Comment by irsat000** [comment]
Sadly, no. However, if anyone is willing to mess with it, I don't mind.

**Comment by Nessuno2000** [comment]
Is it possible for you to make a userscript? No pressure of you don't want to.

**Comment by irsat000** [comment]
I don't want to make excuses, I want to work on something else.
