### ISSUE TITLE
Feature request. -  Allow you to download every option into single compressed folder for making regular complete backups.

### ISSUE THREAD

**Issue by strunberg** [irsat000/CAI-Tools#23]
I was wondering if you would willing to add the option to download every available option with a single click?

I come from Chat GPT RPing and too many times the developers did something in the background that would bug out a RP forcing me to start all over again.

I like what you have done so far, but I have 10 or so active characters, and by having to manually download 7 items each is a pain in the ass.

Lastly , could you please add the option to download the settings into a format for word processor?

**Comment by irsat000** [comment]
I believe such a feature would be a bit off. I don't think this has a use case for the rest of the users. Instead, open the console with F12 and selecting console tab and copy, paste, enter this;

`document.querySelectorAll('[data-cait_type]:not([data-cait_type="character_settings"])').forEach(a => a.click());`

As for word processor, I have no idea what that is.
