### ISSUE TITLE
Do you ever plan to add support for Firefox mobile?

### ISSUE THREAD

**Issue by ArcticNiko** [irsat000/CAI-Tools#25]
**Do you ever plan to add support for Firefox mobile?**

If you don't already know, Firefox has native support for mobile extensions, and nowadays, it's fairly easy to port your Firefox extension onto there. Even Stylus and Tampermonkey is there!

I am aware of the solution provided in the readme.md, stating that you can use "Kiwi Browser" to install CAI Tools, but I'd honestly like to stick with Firefox instead. If you could provide this, that would be massively appreciated.

Thank you!

**Comment by irsat000** [comment]
I always check the mobile support box when uploading to Firefox. But I couldn't really figure out where to find my extension. It only showed me a bunch of popular extensions and I just gave up. If you know more, please share and I will make it possible.

**Comment by ArcticNiko** [comment]
Alright.
