### ISSUE TITLE
Not working on Orion Browser

### ISSUE THREAD

**Issue by SkyanUltra** [irsat000/CAI-Tools#27]
I've used this to port over bots and download character cards before, but I decided to try it on mobile with a browser that supports both Chrome and Firefox extensions. After trying both though, the CAI tools menu never popped up, even when requesting the desktop site.

**Comment by irsat000** [comment]
Try Kiwi browser on mobile.

**Comment by irsat000** [comment]
Extensions are generally built for desktop to be honest. There isn't a code change that I can do. If there is a browser that allows you to download extensions, it's at their mercy.

Try to find a browser that supports extensions. Kiwi works, I don't know if Kiwi is availavle on apple's App Store.
