### ISSUE TITLE
Doesn't work with a paid subscription.

### ISSUE THREAD

**Issue by teecil** [irsat000/CAI-Tools#3]
As far as I understood CAI Tools does not work with a paid subscription, because the subscription is at **plus**.character.ai, not **beta**.character.ai

Are there plans to add support for the subscription domain?

**Comment by irsat000** [comment]
Thank you, v1.4.0 will fix that. Unless Google keeps me waiting, you should be able to use it in 1-2 days. If it won't work after that, please message me again. I don't have the plus membership, you gotta test it :)

**Comment by teecil** [comment]
> If it won't work after that, please message me again.

I'll be sure to let you know if I have any issues after the update. Thank you.

**Comment by irsat000** [comment]
Did you update it? Did it work?

**Comment by teecil** [comment]
Yes, I upgraded. I poked all the buttons and they all work. Thanks for the promptness.

The only thing I can point out is that when I used the previous version (I created an unsubscribed account for this), when I downloaded Raw Dumb (json), I had the AI Character Editor open automatically in a new tab. It's not happening now.  
Just thought you should know, because for example, when downloading Raw Dumb (anonymous), I am still prompted to automatically open the CAI Dump Uploader.

**Comment by teecil** [comment]
> Did you update it? Did it work?

Yes, I upgraded. I poked all the buttons and they all work. Thanks for the promptness.

The only thing I can point out is that when I used the previous version (I created an unsubscribed account for this), when I downloaded Raw Dumb (json), I had the AI Character Editor open automatically in a new tab. It's not happening now.
Just thought you should know, because for example, when downloading Raw Dumb (anonymous), I am still prompted to automatically open the CAI Dump Uploader.

**Comment by irsat000** [comment]
It's because I deleted the Character Creation redirection. It shouldn't be doing it automatically, though.

It asks id you want to do it, if you click okay, it opens in a new tab. If you ckick cancel, it doesn't ask again until you close your browser.

I don' t know why you are facing this issue, what kind of platform are you using? Chrome, firefox, kiwi browser, other browsers?

**Comment by teecil** [comment]
Yes, I was inaccurate in my definition. By "open automatically in a new tab" I meant that it asks if I want to do it.

To rephrase, it stopped asking me if I want to open the Character Editor. I tried reloading the browser, nothing.
I tried it in Google Chrome with a Plus account, and in Microsoft Edge with a basic free account. It didn't pop up anywhere.

Was there a plan to remove this pop-up question, or is it just me?

**Comment by irsat000** [comment]
I believe I made it clear why I removed it in the first paragraph.

You no longer need that app to create a character. You can use this file to upload and edit on it too.

I will add a character card downloader in the next update.

**Comment by teecil** [comment]
> I believe I made it clear why I removed it in the first paragraph.

Oh, I'm sorry. English isn't my first language, so I may have misunderstood. Thanks anyway.

**Comment by irsat000** [comment]
Somebody told me it's not working with plus. the paid membership. Is it still working on your browser?
