### ISSUE TITLE
Issue with memory manager

### ISSUE THREAD

**Issue by coconut78** [irsat000/CAI-Tools#31]
whenever i try to save a memory, the following message pops up : 
<img width="316" alt="cai" src="https://github.com/irsat000/CAI-Tools/assets/161369328/f0d0446f-59a3-4ba1-95b1-0e4ba77d8061">

**Comment by coconut78** [comment]
also i tried the solution which was submitted 3 days ago, still didn't solve anything

**Comment by irsat000** [comment]
Could you please press F12, then open console, and see if you can spot any related errors? You can just copy paste the entire thing if you can't see it.
