### ISSUE TITLE
Feature request (Since im ignored on the discord)

### ISSUE THREAD

**Issue by Invaliduser81** [irsat000/CAI-Tools#32]
Could you create a feature that will "Export all personas" or "export current persona" as a .txt file or as a zip file containing all the txt files, being named a persona and the corresponding details addressed to them :) If you need me to explain it more I will since im a horrible explainer.

**Comment by irsat000** [comment]
I think you are ignored in character.ai's feature requests channel, I remember seeing this post. But I am not sure what is the use case, it must be widely used to motivate me enough to add it.

**Comment by Invaliduser81** [comment]
> I think you are ignored in character.ai's feature requests channel, I remember seeing this post. But I am not sure what is the use case, it must be widely used to motivate me enough to add it.

Yeah I guess that makes sense, its just something I thought would be nice, originally only though about it because I have over 20 personas im scared of losing but too lazy to make organized txt files of them. I guess ill give up on it

**Comment by irsat000** [comment]
Thank you for your understanding. It's just I have too many things to add and fix so I must do sacrifices.

**Comment by Invaliduser81** [comment]
> Thank you for your understanding. It's just I have too many things to add and fix so I must do sacrifices.
