### ISSUE TITLE
neither chat duplicate option working at all

### ISSUE THREAD

**Issue by MitchTOM1409** [irsat000/CAI-Tools#35]
when i try them (on firefox 123.0.1) it very helpfully says "Error when trying to create new chat."

everything else seems to work fine tho

**Comment by irsat000** [comment]
Yes I am aware. I wish I could find out why haha. The thing is, it doesn't give any error or information, making it 100x harder than what it should have been. You could do it in chrome and switch back to firefox as a temporary solution.

**Comment by irsat000** [comment]
https://addons.mozilla.org/en-US/firefox/addon/cai-tools/

Remove the Legacy version and try this one.
