### ISSUE TITLE
[Firefox, chat2] Cannot save memory

### ISSUE THREAD

**Issue by SSUPII** [irsat000/CAI-Tools#38]
```
Screenshot this error please;  TypeError: charSettings is undefined
    MemoryManager moz-extension://8a2b2869-3c23-45e9-99e8-fc22558b067f/scripts/content.js:785
```

What else can I provide?

**Comment by irsat000** [comment]
Thank you for the eloborate one, this much is probably enough. I will take care of it.

**Comment by irsat000** [comment]
I was unable to replicate the issue, but maybe it's because of the version. Those codes are not on 785, they are in line 1800+

Could you update your extension to v2.2.2 and try again?

**Comment by SSUPII** [comment]
The add-on was at version 2.1.1. Don't know why didn't pick up the latest version.

I manually checked for updates, installed it and the error message disappeared. Thanks.
