### ISSUE TITLE
Uploading the tavern chat doesn't work.

### ISSUE THREAD

**Issue by CCCCCCCCC8** [irsat000/CAI-Tools#4]
I download the conversation as tavern ai conversation and i get a .json file and i try to upload it to tavern ai but it doesn't work. maybe im doing it wrong? i've tried it many ways but it hasn't worked so far. thanks for your time.

**Comment by irsat000** [comment]
It's supposed to download a _.jsonl_ file. Oobabooga chat is the one with _.json_ extension.

In previous versions, I overlooked a part of the code that caused this _.jsonl_ blob here to be downloaded as _.json_. I fixed it in latest versions, try updating the extension.

`const blob = new Blob([outputString], { type: 'application/jsonl' });`

**Comment by irsat000** [comment]
Did it work?

**Comment by CCCCCCCCC8** [comment]
sorry for late response, just tested it out and it worked thank you
