### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sk337** [irsat000/CAI-Tools#40]
add an option to make the side bar transparent and add a slider for blur radius an example of what i mean this can be done by setting background color to rgba(0,0,0,0) and and set backgorund-filter to blur(15px)
![image](https://github.com/irsat000/CAI-Tools/assets/79583517/436c5e4a-87b6-403b-9085-cb440a09c5c0)

**Comment by irsat000** [comment]
Cool. How about semi-transparent black background like the right panel from before? I guess they are ditching the fixed right panel, mine is still there in chrome but in opera it can be closed and opened like yours.

**Comment by sk337** [comment]
i guess that would be find i can use my custom css if i need to

**Comment by irsat000** [comment]
Have you updated it? Is the new version ok?

**Comment by irsat000** [comment]
Awesome. Sorry for not going all the way with sliders, it's just it would take so much time.
