### ISSUE TITLE
Background & font manager not working on new site, but works just fine on old site

### ISSUE THREAD

**Issue by ArcticNiko** [irsat000/CAI-Tools#41]
**Premium Status:** Free Trial

**Bug:** The background & font manager refuses to work on the new website, but works fine on the old website.

_BACKGROUND MANAGER_
I can interact with the UI just fine, but no changes apply. When I reload, my changes are gone.

_FONT MANAGER_
The window is blank.

# SCREENSHOTS
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/699427fa-59d2-476a-9dc8-e68ef2e8a6b5)
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/66840518-487c-4fe4-8b52-734917b9416a)

For reference, this is how it would look on the old site.
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/ef31157c-1d49-4fda-ad36-9feea42981f6)
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/5b330861-2798-42f2-8e37-6ee6da189928)

**Comment by irsat000** [comment]
I guess you got a new website update earlier than me. They are doing regional updates, it's a good practice for the company. Hell for extensions. I can't spot the issue without having the new update of the website.

Thanks for the report, I will fix it.

**Comment by irsat000** [comment]
By the way, why is your starter list empty? Old site should be working fine right? Did you delete them yourself?

**Comment by irsat000** [comment]
Your list was separate but that's okay, starter is just there to give an idea. I could fill it with a nice library but most images have rights these days. Better safe than sorry.

**Comment by irsat000** [comment]
Is it fixed? If it's not, can you execute this with enter button in chrome developer console? Then refresh the page. (F12 > Console)

```
window.indexedDB.deleteDatabase('CAITools')
```

**Comment by ArcticNiko** [comment]
Sorry for the late response, I didn't see it.
But after running that command, (all of my needed settings were stored on the old site, so it's alright) everything seems to work fine now, thanks!

**Comment by irsat000** [comment]
Then I will just add some validation codes so it checks and fixes itself. If it happens to you, it can happen to a lot of people and I can't just make them run console command to fix it.
