### ISSUE TITLE
Big avatars make the avatar low quality, but I know why and how to fix it

### ISSUE THREAD

**Issue by ArcticNiko** [irsat000/CAI-Tools#42]
# The problem
As an example, look at this.
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/9399c1e1-765a-4c69-940d-a988562dd152)
As you can tell, the image looks super low quality. Even if you set it to medium size (pictured below), the image quality will still look pretty mushy!
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/211e2b9e-0bbe-4231-bb60-66c395f09de5)
And if you're wondering, yes, the new website is indeed impacted by this as well.
![image](https://github.com/irsat000/CAI-Tools/assets/107579979/73f02b7a-eead-4e88-a2c3-d66d42c167e1)
# The solution
The problem lies in character.ai itself, not the extension. character.ai is requesting a 80px avatar image, which is essentially being stretched onto a 90px or 140px element (depending on your avatar scaling level), which isn't good.

So what's the solution? Well, the simplest one would to simply change the `src` attribute to request a higher-res image, like a 200px avatar or 400px avatar. 200px would be okay since the biggest option caps out at 140px, and 400px could ensure sharpness.

However, I'd recommend against that since it doesn't follow responsive image design. For example, although I said that 200px would be okay since the biggest option scales the avatar at 140px, that might not be be true if you were using, let's say, a monitor with 200% display scaling, where the image element is basically being rendered at 280px. However, simply requesting 400px wouldn't be a good idea, as one might not have high enough display scaling for that to be needed, and that might as well end up wasting performance and bandwidth.

Admittedly, only by a _tiny_ bit for both, but regardless, there are better options.

To combat this using responsive image design, you can use `window.devicePixelRatio`, which gets the currently display scaling and browser zoom. To use this, you could setup an `if` statement that's similar to this: (or it can be this exact if statement)
```js
function getProperAvatarRes(scale) { // scale = avatar scaling option. 1 = large, 0 = medium
    let result;
    let renderedSize = (scale == 1? 140 : 90) * window.devicePixelRatio; // avatar element rendered w/ display scaling
    if (renderedSize <= 80)
        result = 80;
    else if (renderedSize > 80 && renderedSize <= 200)
        result = 200;
    else if (renderedSize > 200 && renderedSize <= 250)
        result = 250;
    else if (renderedSize > 250 && renderedSize <= 300)
        result = 300;
    else if (renderedSize > 300)
        result = 400;
    return result;
}
```
This snippet calculates the size that the avatar will be rendered in on screen, and determines the appropriate avatar resolution to fetch for it.

**Comment by irsat000** [comment]
Yeah, it just completely got out of my mind. There was no need to sweat yourself so much. 400px won't waste your performance, don't worry about it. Instead of 80, I will go for 400 for the image url like; [https://characterai.io/i/400/static/avatars/uploaded/2023/1/21/Qzkvr_QbX4hU0GNrjiN7jpj8jR0TXEIqkWyQznAjIOA.webp](Example avatar)

**Comment by irsat000** [comment]
It has proper caching system so the avatars are fetched only once and used over and over again from the cache. It's finished by the way, looks pretty good. I want to fix Char Catalog button disappearing from the mobile left panel menu and then it will be updated. (If you are curious, it disappears because a new panel is created each time on mobile version)

**Comment by irsat000** [comment]
![animatedAvatar](https://github.com/irsat000/CAI-Tools/assets/38238671/843a5683-9c86-4bb1-9df6-d6ab32bb91f3)

**Comment by ArcticNiko** [comment]
Alright, thank you!

And I guess you're right about the 400px avatar thing, because even though it's generally recommended strive to use responsive image design (or responsive web design in general) no matter the severity of the benefit, from my own testing, using 400px does clear out some compression artifacts 200px may have.
