### ISSUE TITLE
Greedy ass mf (read this)

### ISSUE THREAD

**Issue by Theclarkus** [irsat000/CAI-Tools#45]
PAYING MONEY JUST FOR FONT COLOURS? PAYING MONEY FOR MAKING IT EASIER TO READ SPEECH AND ACTIONS? WTF
YOUR NOT MR KRABS
if its something that requires money have an actual reason

**Comment by Theclarkus** [comment]
I am not fucking paying for a font or colours
before you say anything your just proving your greedy as fuck

**Comment by irsat000** [comment]
Lmao.

**Comment by irsat000** [comment]
Mr Krabs was a good one
