### ISSUE TITLE
Lost the Main Part of Chat Logs

### ISSUE THREAD

**Issue by shikireal** [irsat000/CAI-Tools#48]
The response stuck problem also happened to me. While replicating over 10000 chat logs, my screen protection interrupted the process, and it got stuck at around 300 out of 10983 logs. Not familiar with how it works, I refreshed the page to try to fix it, but now only 300 logs remain, and the others are gone. I didn’t know any interruptions would prevent restarting the replication. How can I retrieve them? Any assistance would be greatly appreciated.

**Comment by irsat000** [comment]
It's not lost in any way. Just go to history and find the original.

**Comment by irsat000** [comment]
A more detailed response here; It's as it says, "cloning". It creates a new chat and starts writing there. If it's cut unexpectedly, it's still copied up to that point in the new chat. If you go to your character, it will show the latest interacted chat. You can find the original chat in history panel.

https://www.patreon.com/posts/save-and-name-105175061
Also check this out, I have a plan for saving conversations.

**Comment by shikireal** [comment]
Oh,I was too anxious and forgot about this feature.Thanks anyway.But the issue of getting stuck through replication still persists.

**Comment by irsat000** [comment]
Yes, I am working on that. I believe if I can replicate it my own, I will have a much higher chance at fixing it. The code fix is relatively easy, it's not knowing what causes it.

**Comment by shikireal** [comment]
That sounds super promising. If you need the code for this issue, just let me know how I can help. Maybe I can copy it somewhere?

**Comment by irsat000** [comment]
If you don't have any sensitive information in there, you could send me the Offline Chat file. Import Chat feature works with the same logic as chat duplication.

I don't have a chat that long but I put a character in an infinite loop of generating messages using some code. It should give me a similar problem soon. It's going at it for like half an hour right now. If it continues to work, I can try yours.

**Comment by irsat000** [comment]
Just when I wrote this, the WebSocket closed on its own. But didn't give an error like the other issue thread gave me. It just stopped at 48th minute. It's hella complicated.

**Comment by shikireal** [comment]
Well,>< the contents might be a bit too sensitive to share. Is it okay if I share another character's logs instead? They have about 600 chats and less sensitive interactions and don’t have responses generation issues.It would also be great if there's an alternative way to fix it.

**Comment by irsat000** [comment]
Mu looped code generated a couple 15k chats no need to worry.

Damn, it actually finished duplication without a single error. How am I going to test this thing.

The version I am using should cover all cases by the way.

**Comment by shikireal** [comment]
Excuse me for not knowing the code, but how can you find the exact error from two different offline histories? Is it possible that a specific chat log reported the error? I thought it was a server issue. I’m okay with giving you my chat profile as a sample, but I’m not sure if providing chats that aren't the exact ones where the error occurred will affect your troubleshooting.

**Comment by shikireal** [comment]
Just want to let you know I failed again . I spent all night replicating full of chats, but it got stuck at around 700. I almost give up on replicating them all, so I just did the last 100 to keep the conversation consistent. Anyway, thanks for your support!

**Comment by irsat000** [comment]
How?! What does it say?

**Comment by irsat000** [comment]
Did you use the one I sent today? To other thread.

**Comment by irsat000** [comment]
![image](https://github.com/irsat000/CAI-Tools/assets/38238671/8add06d0-5664-4caf-97c5-e994d3257148)

I used it many times, this 14k chat threw server errors and lost internet connection many times. And still came on top and completed all.

**Comment by irsat000** [comment]
Did it work for you as well?

**Comment by d7c0** [comment]
> The response stuck problem also happened to me. While replicating over 10000 chat logs, my screen protection interrupted the process, and it got stuck at around 300 out of 10983 logs. Not familiar with how it works, I refreshed the page to try to fix it, but now only 300 logs remain, and the others are gone. I didn’t know any interruptions would prevent restarting the replication. How can I retrieve them? Any assistance would be greatly appreciated.

You can download all chats at once? Or do you have a chat with 10K posts?

**Comment by irsat000** [comment]
When you refresh, it redirects you to the latest interacted chat. Which is the newly created clone chat.

You just need to open the history and open the second chat in line. Nothing is removed.

**Comment by irsat000** [comment]
I generated a 15k chat to replicate the issue. I have experienced it with different errors and fixed all that I have seen.

Did you try the zip file I attached in the other issue thread?

Disable the current one and install this unpacked extension. You can google how to install unpacked extension on chrome.

If you can't, don't worry. Update is coming soon.

**Comment by irsat000** [comment]
Can we close the issue?
