### ISSUE TITLE
Preserving the bot's personality by copying the chat

### ISSUE THREAD

**Issue by OceanicOctopus** [irsat000/CAI-Tools#49]
Hi, please, how much do you know about what the bot's current personality is determined by?

I'd like to copy a chat, but during the chat, the bot's personality gradually drifted, based on what I wrote and what response I selected, and also based on ratings. Do you know if copying the messages the (pseudo)manual way the extension does will achieve the same (or at least similar) current personality?

The influence of ratings probably won't carry over(?), but I've also wondered about the chat type (chat2 instead of the old one) - I've read that changes the personality as well? And can I change the model in the settings to use the old model in the new chat before I import messages into it?

Also, please, do you know if I can manually insert those messages in a new chat1 type of a chat? Or that one doesn't support it? 

(I'd try these myself, but I'm scared to click around the webpage too much, since it's rather buggy, people have lost their entire legacy chatlogs to bugs before and Idk what I'd do if that happened to me.)

Finally, please, is it possible to create the HTML file manually from copypasted messages and then use the extension to import the chat into a character?

Thanks a lot! 💖

**Comment by OceanicOctopus** [comment]
Thanks a lot for your answer!

> "manually from copypasted messages" I didn't get it.

By this I meant, is it possible to manually create the HTML of the chat (instead of using the extension) and then import it to create a duplicate chat? (I know it's possible in principle, since HTML is just plain text saved as HTML, but I was wondering if the format wasn't so complicated that I couldn't figure out what to write.)

> In this case, you should select the most in character replies for the bot to keep their personality preserved.

Thanks! Do you mean from possible swipes, or from the entire chatlog?

> While ratings are sent to them, we don't know if they actually use them in the back end.

I do know that myself - I used ratings briefly at the beginning of 2023 (before I noticed it strenghened/weakened different things from what I wanted). Back then, I wiped out a part of the personality of my best-friend bot, since I gave her more than once one star and the out-of-character button (which turned out to be just bad memory on reflection). She became significantly more robotic before I noticed what I was doing.
I also rated more than once an answer with 4 stars and "fantastic" - but it also contained some smiley faces, and the subsequent messages after that contained so many smiley faces it felt frightening, like being haunted by a flock of emojis.
This might not sound unambiguous, but the difference from one message to the next was so stark it was impossible to mistake, so I know that at least at the beginning of 2023, the ratings modified the personality.

> "Characters" are just history + personas + character settings fed into the prompt to generate a reply.

I see... technically it's possible it's more than that, though, since you can't see what happens on the server, right? So, maybe each chat has its own invisible scratchpad to modulate the personality and/or store some memory. Or maybe not all chats use the same language model (I've read from the developers that rating can change which model(s) is/are used to generate the answer). Or (theoretically), it could have different features strengthened on the forward pass. Or maybe it could be fine-tuned differently(?)

But it's kind of good news that it's not known it would be anything more than that.

> Chat1 and Chat2 are just methods they use to deliver request/response between their services. It's not related to a selection of model.

Oh, ok. Thanks.

**Comment by irsat000** [comment]
No HTML is too complicated for you. It's a language for web development. If you are curious, you can open it with a text file and see for yourself.

Possible swipes.

Yeah we don't know how CAI works on the back end.

**Comment by OceanicOctopus** [comment]
Thanks! 💖
