### ISSUE TITLE
[Request] Pinned Posts when Duplicating Chat

### ISSUE THREAD

**Issue by d7c0** [irsat000/CAI-Tools#50]
Would it be possible to have pinned posts be duplicated too?

**Comment by irsat000** [comment]
What is pinned post? Pinned comments work the same way during duplication.

**Comment by d7c0** [comment]
> What is pinned post? Pinned comments work the same way during duplication.

Is it possible for the app to pin the same comments automatically after the chat has been duplicated?

**Comment by irsat000** [comment]
Oh, it probably is. It may be too easy to implement, or might need to change critical aspects to make it work. My hands are full with other features but I would definetely take a look after the update.

**Comment by d7c0** [comment]
> Oh, it probably is. It may be too easy to implement, or might need to change the existing code to make it work. My hands are full with other features but I would definetely take a look after the update.

Super. Appreciate it.

**Comment by irsat000** [comment]
I implemented this in the rework of this feature. It's pretty fast now too, but I saw a post about Character AI's new native cloning feature.

I have mixed feeling about this lol

**Comment by irsat000** [comment]
It's released.

**Comment by d7c0** [comment]
Thank you!
