### ISSUE TITLE
Only saves 17 chats out of all

### ISSUE THREAD

**Issue by Weoniq** [irsat000/CAI-Tools#52]
First, can't thank you enough for making this extension, it's my savior, lol.
The issue is basically the title. I wanted to save the history of all chats with one bot, and I have 50+ chats with it, but it only saves 17 of them. The same with all the other bots, where I have more than 17 chats.
![17 chats](https://github.com/irsat000/CAI-Tools/assets/172994536/e090852a-60a8-4b24-a845-fa93ed8e4083)

**Comment by irsat000** [comment]
It doesn't include chats with no messages. If not, maybe the site put a limit. If you can see them in history and you are sure they have content, maybe they have pagination for fetching history now. I will take a look.

**Comment by Weoniq** [comment]
Omg, yes, it's because some of those chats turned out to be empty with only the greeting messages.
Sorry for being inattentive, I just saw the number and didn't bother to check the history manually.
Everything is working great, thanks again for your work!

**Comment by irsat000** [comment]
Well, try creating new and adding some messages. Maybe there really is pagination that requires more than one fetching of history. If you see 18, then we can close this.

**Comment by irsat000** [comment]
Awesome. I will still be checking if there is a pagination of course. I wonder what's the limit. Maybe the website itself have a limit and that's why people getting angry about a limit or something.

**Comment by Weoniq** [comment]
Oh, I didn't hear about any limits? I only know that the history doesn't load fully on the new website (only 50 last messages, iirc), but the extension still loads all history. I haven't tried it on my longest chats yet though. The longest chat I saved today was 150 messages, from the new version website, and it saved the whole history.

I only know one issue which persists on both old and new websites and on the app too - the messages that are happen to be the last loaded (when you scroll up to see more history) - they're somehow being changed to their swiped/rerolled versions. This issue gets fixed once I generate a new message or delete the previous one.

I'm not sure which version of those messages gets saved in the history file, but I suppose, the wrong one.
