### ISSUE TITLE
The Chrome Web Store version requests access to read & change data on the chatgpt.com domain

### ISSUE THREAD

**Issue by ArakiSatoshi** [irsat000/CAI-Tools#54]
![Screenshot 2024-06-25 180026](https://github.com/irsat000/CAI-Tools/assets/45124115/f080c233-00a7-4c2d-8e33-40f677459cdf)

I noticed that CAI Tools now requires read and write access to the chatgpt.com domain, something out of the scope of this extension. Can we get a word on that?

**Comment by irsat000** [comment]
Because there is a new features powered by ChatGPT! It's free feature, check it out!

**Comment by irsat000** [comment]
It can basically summarize the chat and remind the bot about past events. Hoped for it to be better than memory manager. We will see how that goes as one click solution but with ChatGPT limitations... I called it (Beta) so please feeback.

Let the issue thread stay here just in case more people have the same question.

**Comment by Gentokiii** [comment]
This is such a great feature idea. I keep getting this error though across different chats. Is there something you need to put into the summary box before hitting "summarize" because that's all I click on. 
![Screenshot 2024-06-26 5 22 48 PM](https://github.com/irsat000/CAI-Tools/assets/173960870/70c25da6-dd5f-4e49-80a1-9093ddc44bec)

**Comment by irsat000** [comment]
It can be due to multiple reasons. It's definetely NOT because filtered/blocked chatgpt response, it would note that if it was.

I will take a look tomorrow. So glad I put (beta) next to it, it would be very embarrassing otherwise hehe

Most likely it's inconsistent. The culprit is ChatGPT's security layer that says unusual activity, as in we didn't provide the correct chat requirements tokens. I made it to try 3 times before giving up, because usually it's a one time thing.

I can hear you say wtf are you talking about. Well, simply the chatgpt request is rejected. Still working on that but I see the same thing on extremely popular chatgpt powered extensions.

**Comment by Gentokiii** [comment]
Haha yeah it's no problem. Thanks for explaining. How does it summarize using ChatGPT though? I thought there were character limits. 

Anyway, I'll definitely experiment with this. Thanks again man.

**Comment by irsat000** [comment]
ChatGPT 3.5 allows about 30-34k characters, I don't know the exact limit but more than that gives error.

So I separate the Character AI chat into 30k character parts. Hence the {{CHAT_PART}} text, each question summarizes a part.

Then we gotta send them as message and Character.AI itself doesn't limit us. But something like 50k character message is bad for bot memory and can give errors, so the summarizes are combined and separated into 4k characters, which is plenty and can be readable by the bot.

Also I just hotfixed the prompt being returned as "summary" problem. Make sure to update to v2.5.1. More hotfixes are required though...

**Comment by ArakiSatoshi** [comment]
Thank you for your reply, I feel bad for coming back to the thread so late. Here are my two cents.

While the idea is great, is ChatGPT really the right tool for summarizing CAI chats? People tend to have NSFW-ish conversations there. While subtle to not trigger CAI's filters, they _may_ trigger OpenAI's and lead to some chats with ChatGPT getting tagged with the infamous ToS-breaking message. Another issue is that ChatGPT might feel biased towards safety and reject the instruction altogether, or ground some scenarios down on its behalf.

May I suggest exploring OpenRouter as an alternative? I believe it should be straightforward for the user with this workflow:

1) Click a "Connect API key" button in CAI-Tools
2) Get redirected to `https://openrouter.ai/auth?callback_url=xxx` ([official documentation](https://openrouter.ai/docs/oauth), [SillyTavern's implementation](https://github.com/SillyTavern/SillyTavern/blob/a410c63333069100aee6d4e4b54196cd6accfa24/public/scripts/secrets.js#L174))
3) Register/login OpenRouter account using a Google / MetaMask account
4) Acknowledge API key creation
5) Return to CAI with their API key automatically saved inside the extension

Then, for the user, it should be the same as the current implementation. For CAI-Tool, it'll be an API request to some free model like `google/gemma-2-9b-it:free` (8k context length) or `mistralai/mistral-7b-instruct:free` (32k context length).

I cannot code, so I'm not sure if any of this can be implemented in a browser extension. I'll give one limitation, though. Some OpenRouter models can be unstable. For example, `microsoft/phi-3-medium-128k-instruct:free` gives much better summarization in comparison to `mistralai/mistral-7b-instruct:free`, but tends to cut off before it hits the EOS token.

Another alternative to explore is [Groq](https://console.groq.com/) which seems to have a free API as well and offers access to `Mixtral-8x7B-32k Instruct`, though I don't know much about them.

That's just one route, and it's up to you to decide if it's worth exploring. Thank you for your time!

**Comment by irsat000** [comment]
It wouldn't be too hard to implement, the extension is quite flexible. What is hard these days is finding a free service with no limit, rightfully so.

I am trying to fix the existing one, then I can add alternatives.
