### ISSUE TITLE
Summarize doesn't work with ChatGPT Plus (Subscription) account

### ISSUE THREAD

**Issue by Mr005K** [irsat000/CAI-Tools#55]
I have tried using the summarize feature with my paid subscription ChatGPT account logged into the same browser, and it always returns this error message
<img width="315" alt="Screenshot 2024-07-03 at 9 50 47 PM" src="https://github.com/irsat000/CAI-Tools/assets/150620619/c73f1936-e207-489b-86e3-c5c563d5fd69">

But when i log into my free ChatGPT account (non-subscription) and try, it works very well. 
<img width="342" alt="Screenshot 2024-07-03 at 9 51 32 PM" src="https://github.com/irsat000/CAI-Tools/assets/150620619/9f324302-f0e9-4486-b088-d405fe934f8a">

I have checked and given permission for the extension to always run on both character.ai and chatgpt.com.

**Comment by irsat000** [comment]
It's probably an easy fix, I will do my research and we will get rid of it in the next update.

Then I will try to figure out how to fix the other gpt issues, and only then I can call it the release version of Summarize feature.

**Comment by irsat000** [comment]
[CAI-Tools-Chatgpt-Fix-Test.zip](https://github.com/user-attachments/files/16101610/CAI-Tools-Chatgpt-Fix-Test.zip)

Could you try this version?

How to install: https://www.youtube.com/watch?v=oswjtLwCUqg

**Comment by Mr005K** [comment]
Tried it, still gives the same error "ChatGPT did not return any summaries".

I disabled the regular extension and loaded this unpacked one as you said.

**Comment by irsat000** [comment]
Diagnosing is important, I will prepare more versions to see what works for you tomorrow.

**Comment by irsat000** [comment]
![error](https://github.com/irsat000/CAI-Tools/assets/38238671/753d68a4-531d-45c6-a50a-687bdb57c31b)

At the very least it should give an error like this. Do you receive anything? I can't find any blind spot to let it slip without giving an actual error.

Also when I change the model choice into something like "lol", it still auto corrects it somehow so it's not about the model choice for ChatGPT plus.

I will continue to study other apps, since they use webpack, it's like I am trying to read Assembly code.

**Comment by Mr005K** [comment]
Nah man, i just get ChatGPT didn't return any summaries, no additional error. on both firefox and chrome. It works on my free account, so really, i am not sure anymore about whats the problem.

**Comment by irsat000** [comment]
Found it. It's because unlike Free tier which requires Access Token, Requirements Token and Proof Token, yours also require Arkose Token.

I don't have a code for the Arkose Token... I guess it's pretty hard to generate too. But at least we know why.

**Comment by Mr005K** [comment]
Oh, i see, that is good to hear that you figured out the problem man, major props, the summary feature has been very useful in improving RP quality, even with my free tier, hope you can get this arkose token thing resolved soon :)

**Comment by irsat000** [comment]
Why bother with automation detection tokens when it can be bypassed anyway smh

**Comment by Mr005K** [comment]
Hey, it works now! On the plus account!

**Comment by irsat000** [comment]
I didn't even change anything :(

**Comment by Mr005K** [comment]
damn, maybe their introduction of GPT 4-o mini changed something? All i know is, i've tested it multiple times, and it works very well.

**Comment by irsat000** [comment]
Hey I have developed a new feature powered by chatgpt. If you test it for me with your chatgpt plus, I will give you premium.

I couldn't find a way to generate human verification (arkose token) but I fixed other tokens and selected the free model that doesn't require arkose token.

**Comment by Mr005K** [comment]
Sure, I’m down to test it for you, dude, we can communicate via discord; that would be better for me. Hit me up @famseizurect

**Comment by irsat000** [comment]
Solved with the power of friendship.
