### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by SolsticeX2** [irsat000/CAI-Tools#57]
Hi there, I keep getting this error message when using the new v.2.6.0

<img width="335" alt="屏幕截图 2024-07-13 192708" src="https://github.com/user-attachments/assets/6233d149-3a18-451a-b261-3949352e7c65">

I was wondering what this could mean.

**Comment by irsat000** [comment]
2.6.0 doesn't use native indexeddb anymore. Are you sure you haven't downgraded after using 2.6.0?

**Comment by irsat000** [comment]
It's also possible if you have both new and old version installed.

**Comment by irsat000** [comment]
This error message doesn't even exist in v2.6.0+ because I deleted it completely, just checked. You have older version installed.

I am closing this in a day, please respond if it's fixed.

**Comment by SolsticeX2** [comment]
Yes, I do believe it was due to me having two versions installed at the same time. Thank you!
