### ISSUE TITLE
Export chat from a private bot?

### ISSUE THREAD

**Issue by undrewatre** [irsat000/CAI-Tools#58]
I'm a little desperate, and have very little knowledge, so bear with me here...

I think a bot I used to chat got privated. I could still search it on google, this is [the one](https://beta.character.ai/chat?char=ReH3drehrnxZBchvv_rAoVnXBhKsrU3BpkPZ13EMWZw). When I open the link I could see the extension pop up for a bit before being redirected to the main page.

Is there any way I can try to export my chats from the privated bot without access to it?

**Comment by irsat000** [comment]
With code it would probably work. But it's too much hassle. That is unless your chat is deleted and redirecting you because of this also.

**Comment by undrewatre** [comment]
I don't think it's deleted. My chats with that bot, I definitely didn't delete. It's just the bot creator privated it, because there's no way to delete a bot as far as I know.

I really wanna be able to back them all up, I have so many chats with that one bot.

**Comment by irsat000** [comment]
Okay I will help you out in a day or two. We can trick my extension into downloading another chat. Since you are authorized for that chat it's possible. But may not be possible if the lack of authorization of the privated bot prevents it.

**Comment by undrewatre** [comment]
Thank you so much, I appreciate it! I'll be waiting. Hopefully it'll work, hoping I can export them all to offline chats.

**Comment by irsat000** [comment]
Okay, do this; Open a random character on CAI. Open the browser console using F12 on chrome and clicking on Console tab.

`history.replaceState(null, '', 'https://character.ai/chat/ReH3drehrnxZBchvv_rAoVnXBhKsrU3BpkPZ13EMWZw');`

Paste and enter this. It will update the url without going there. Then open the CAI Tools menu and click "Start fetch" under history. If it succeeds, shows the number of chats and all, then it's great. Click "Offline history" after it's finished and Voilà.

**Comment by undrewatre** [comment]
It showed me this when I tried on my Firefox:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at (link) (Reason: CORS request did not succeed). Status code: (null)

**Comment by irsat000** [comment]
You are in beta. website right? They are technically different websites, it's considered "cross-origin" and browsers have restrictions for that. Try with the new design site.

**Comment by undrewatre** [comment]
No, I'm actually using the newest website? Without beta. or old. in the url.

**Comment by irsat000** [comment]
I tried with chrome, mine worked. Of course it said there is no history because I never chatted with it but at least it didn't say I am unauthorized for that character or something.

**Comment by undrewatre** [comment]
OH MY GOD IT WORKED ON CHROME. DUDE, YOU ARE A LIFESAVER. Thank you so much!!

You should definitely make this a feature on the extension itself?? People on reddit go through the same thing, and I think they would really appreciate it if their chats of privated bots can be restored too (to a html file, of course). I don't actually know c.ai team's stance on using extensions but I would definitely spread the word about this if you'd like, so it'll help more people!

**Comment by irsat000** [comment]
Yea maybe. I am glad it was a success, have fun.
