### ISSUE TITLE
Downloading the saved chats not working? 

### ISSUE THREAD

**Issue by TenshiW** [irsat000/CAI-Tools#6]
I've been using it fine last time but today it just didn't work?? Like the download button during the chat works but at the saved chats, there's a box appears that says: "Failed to intercept CAI. Try reloading." And when reloaded, the saved chats just don't appear but you can press the tool although it doesn't work. Is it just me or is CAI preventing downloading saved chats now? I tried with a test bot so the chat log wouldn't be long but yeah, it doesn't seem to want to load up the chats and download them? Sorry if this isn't a real problem/issue! (Could just be me :"D) 

![Screenshot (1111)](https://github.com/irsat000/CAI-Tools/assets/136673870/32b4e580-031f-40c1-b9a1-d3da07d4dff6)

**Comment by irsat000** [comment]
Thanks for letting me know. The developers changed a request header to "histories_v2" apparently. You should have no problem with v1.5.3, try again after it's approved by Chrome and Firefox.
