### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by jazziethejazz** [irsat000/CAI-Tools#60]
![Screenshot 2024-07-20 213446](https://github.com/user-attachments/assets/4a6d1191-22bd-4ce4-9f70-d3cb3d29b935)
idk how this happened, but the bg wont work so i think it broke somehow as i just refreshed the page. what should i do about it?

**Comment by irsat000** [comment]
Yeah, I have noticed it immediately actually. It was an instant fix. I will just make a hotfix version for it as I continue to work on the other things.

**Comment by irsat000** [comment]
Have you tried the new version? It's released.

**Comment by jazziethejazz** [comment]
yep! but theres either a bug with c.ai or the extension as when the trial ends and the background disappears, the functions under the message get a little hidden
![image](https://github.com/user-attachments/assets/d6de6576-8be3-46fd-baf1-4dc9ce8a6830)

**Comment by irsat000** [comment]
That must be the regenerate icon, shifted under the message container that contains message box. Mine looks fine.

![image](https://github.com/user-attachments/assets/1b15a5db-870f-473a-b7b2-b8f5878f5405)

But I know the reason, it happened to me a couple of times. It seems to be the website itself, after refreshing or some time passes it goes away. Just in case, let me ask you, is this constant?

**Comment by jazziethejazz** [comment]
i think so, it hasnt disappeared yet as it was happening yesterday, should i continuously refresh or wait another day?

**Comment by irsat000** [comment]
Well it certainly isn't my extension, because it has no code that does this. The fix I made was simply making the container's background color that they added randomly go away.

**Comment by jazziethejazz** [comment]
its alright now!

**Comment by irsat000** [comment]
Would you like to share what happened?

**Comment by jazziethejazz** [comment]
i think it was just the zoom, though its weird. the zoom in was fine before, so i sent a req to c.ai anyway. ty for your help!
