### ISSUE TITLE
[Request] Save + Remember CAI Tools Button Location

### ISSUE THREAD

**Issue by JoLiKMC** [irsat000/CAI-Tools#61]
### Please, describe your suggestion.
Please, add an option to save and remember the location (or relative location) of the *CAI Tools* buttons.

### How do you think would this benefit users?
Some users like myself want those buttons to be in a specific location between sessions and chats.  If this were added, it would save users a few seconds, here and there, as they wouldn't have to keep manually moving it back to where they want it.

### Any closing thoughts or comments?
I just downloaded *CAI Tools* and I noticed something.  The little blue button and the "move me" button always resets to about 20 x 20 pixels from the top-right of the browser window whenever the user changes chats or refreshes the window.  This is just a small irritation for someone like me, as I like optimizing the available space on the screen.

That aside, this suite of tools is really amazing!  Thank you, and I hope you don't mind my suggestion!

**Comment by irsat000** [comment]
Yeah I can do that!

**Comment by irsat000** [comment]
![image](https://github.com/user-attachments/assets/790d3bc9-3e48-4a55-ab03-2e40d60e3dfa)

Seems to be working perfectly. It also has precautions to keep it in the page.

Will be in the next update for sure.

**Comment by JoLiKMC** [comment]
Fantastic!  Thank you so much!  I hope it wasn't hard to implement, though.

**Comment by irsat000** [comment]
Added in the latest version.

**Comment by JCollins2048** [comment]
I hate to bump this, but the option to save the icon position seems to have vanished.

Was it removed due to some v3 limitations, or was it a case of "nobody used this"?

**Comment by irsat000** [comment]
Since I remade the entire CAI Tools, it naturally vanished. This is one of the things that will gradually come. Right now I am working on multiple errors and going to add more changes. I will add this too but naturally it will take time until it's at the top of my list.

This can stay open, I will make this change again.

**Comment by JCollins2048** [comment]
I'd *like* to reopen it, but I think it's too old for me to do that.  Button's greyed out, ha hah.

**Comment by irsat000** [comment]
Yeah it was a beautiful blue button, it was wider too, it got osteoporosis, comes with age.

**Comment by JCollins2048** [comment]
I mean the "Reopen Issue" button here on the *GitHub* page.  It's fine, though, heh.

**Comment by irsat000** [comment]
I made the feature while fixing flip issue when the button is put on the bottom. Button changes:

1. Allows mostly being hidden, doesn't reset like before from a single pixel being off screen
2. Saves the button location every 5 seconds
3. When bottom left, it puts the menu on the icon's top right. So it's always in the screen

I will release it in a day or two. No need to reopen the issue.
