### ISSUE TITLE
Summarize not_logged_in error

### ISSUE THREAD

**Issue by pawsitronic** [irsat000/CAI-Tools#62]
I'm logged in to ChatGPT, but I keep getting this error when I try to use the Summarize feature. I have checked the extension settings to ensure the permissions are on. I'm using the Firefox version.

<img width="259" alt="Screenshot 2024-07-25 175834" src="https://github.com/user-attachments/assets/43ae999b-343d-41f9-92b8-c3091eb3bee9">

**Comment by irsat000** [comment]
Like you go to Chatgpt website, click on the extension and allow on this site?

**Comment by irsat000** [comment]
Feature is deprecated, but I am working on a new feature that utilizes it.
