### ISSUE TITLE
Access Token is not ready yet.

### ISSUE THREAD

**Issue by ribbionraving** [irsat000/CAI-Tools#63]
What does this mean? Is there a queue, how do I see that? Will I get a notification when its done? I can't find any information on this anywhere please make this information transparent. Sorry if this has been asked before.

**Comment by ribbionraving** [comment]
Nvm it just takes a minute to set in. I was worried I maybe downloaded something harmful to my computer when I saw that.

**Comment by irsat000** [comment]
Access token is your session. It all happens in your computer, no worries. Every action in CAI requires that token.

But 1 minute is strange, it should be ready as soon as page loads, like 3-5 seconds or something.
