### ISSUE TITLE
Couldn't get character's name/Unexpected CAI Tools error

### ISSUE THREAD

**Issue by yeojachingu309** [irsat000/CAI-Tools#65]
Hello, I apologize if this is a simple issue, but I'm not sure how to resolve it. I'll try to explain as best I can. 

I am currently using CAI tools on Google Chrome (ver. 2.6.2 I believe). 
I tried to download chat history but whenever I open the CAI tools box it gives me 'Unexpected CAI Tools error, please report on Github'. Right after that, I still see (Ready!) next to the Update button. 

I also tried to fetch chat history, but each time I get the error: Couldn't get character's name. 

Funny enough, I got the errors and was still able to download the history once for a different public bot, but not again for a private character. Am I doing something wrong?

**Comment by irsat000** [comment]
I will try to replicate it. Maybe they changed the character name field in the code or something. Because I never got this error before.

**Comment by irsat000** [comment]
I am not receiving the error, could you check again? Maybe it was a server outage.

**Comment by audmrod** [comment]
Hello, I am a new user utilizing CAI tools in chrome and I am receiving the same error "Unexpected CAI Tools error, please report on Github" even though it say 'Ready!' 

Any ideas on how I can fix this? Thanks!

**Comment by irsat000** [comment]
Explained in an another issue thread.

The code is slightly outdated. It will be fixed in the new update.

**Comment by audmrod** [comment]
Sounds good! Thanks for the update

**Comment by irsat000** [comment]
Fixed both chat and history. If you hang in there, I will push it with the other changes in a couple days. Of course there is also google review delay.

I removed 200 miliseconds throttling that eased it for 429 (too many requests) error. It had error handling for that btw, it wasn't an issue. Now that we don't receive that like back then, it can be far faster especially for downloading history.
