### ISSUE TITLE
Memory manager not working after v2 was added

### ISSUE THREAD

**Issue by Sarah096** [irsat000/CAI-Tools#69]
Before v2 was added it was working great. Now, even if I turn off v2 and go to v1 the memory manager doesn't give memories to the AI. It's very frustrating. I know this because I made the frequency 4 and tapped it for 5 minutes and no memory reminders appeared. Please fix this.

**Comment by irsat000** [comment]
I will take a look. No error messages I presume?

**Comment by Sarah096** [comment]
No error messages. It just doesn't work

**Comment by irsat000** [comment]
Have you tried it with a new character and new chat? It seems to be working but it might be just me. If it still persist, could you do "Right click, inspect, console tab, see if there is any error about that something like Screenshot this error:"

**Comment by irsat000** [comment]
I tried Opera, Firefox, Chrome, Mobile Firefox and they all worked. But Kiwi browser didn't work. With a few tests, I figured out it was the web socket interception logic. I will work on it.

**Comment by irsat000** [comment]
Good news again, I deleted wsHook library that I was using and made my own code, I tested with Kiwi browser and now it's working! I will make it more flexible and open to upgrades, then it will be fixed entirely.

**Comment by irsat000** [comment]
Is it fixed?
