### ISSUE TITLE
not able to download bot (rawdump)

### ISSUE THREAD

**Issue by NanaNemNem** [irsat000/CAI-Tools#7]
some bots on C.ai give me the error Data is empty or not ready. Try again later. when attempting to download them as rawdump json files.

![hhhh](https://github.com/irsat000/CAI-Tools/assets/139947796/0f896844-d89c-4216-bacc-93ef30066c82)

Additionally, some bots will have the CAI Tools button available without having to go into saved chats to download the bot.

![image](https://github.com/irsat000/CAI-Tools/assets/139947796/b004a249-f44c-4551-9def-e7b43ce2ab98)

I'm not sure what causes it and I've been trying to experiment around to find a way around it but honestly, I don't know if I am being stupid or if there really is something wrong. From what I've found, bots I have previously chatted with have had no issues downloading but if I wanted to download a new bot I am pretty much S.O.L in this situation.

I attached a few images too in hopes that this could help you understand the issue I am having.

**Comment by irsat000** [comment]
There are two menus. If's perfectly fine if you can see the button in conversation page aswell. You can download your characters there directly. You no longer need dump or anything anymore unless you are scrapping data.

**Comment by irsat000** [comment]
It's okay, I found the issue. New character.ai update introduced a new chat page, if you look at the url adress in new characters, you will see character.ai/chat2 path. Unfortunately the page structure in the codes are very different. I will make a universal button that works for all soon.

**Comment by NanaNemNem** [comment]
So then will it be a bit before certain characters are downloadable again or is there something I can do to download characters now?

**Comment by irsat000** [comment]
Yes, for now you can change this `character.ai/chat2?char=[characterID]` to this `character.ai/chat?char=[characterID]` by hand. It doesn't work sometimes, but going back and forth between other pages like histories fix it. It will appear like before.

**Comment by irsat000** [comment]
It will take a lot more time than I anticipated. These two are completely different pages, they use different APIs and data formats to fetch the conversations. They just can't be satisfied with their own work. Or they are just trying to look busy by changing the website to keep milking the unlimited funds.

**Comment by NanaNemNem** [comment]
Alright, thank you! I appreciate it

**Comment by NanaNemNem** [comment]
and honestly? Its probably the money, you saw how fast Cai put up a paywall

**Comment by irsat000** [comment]
Uploaded the new version. Hopefully, it works for everyone. Check it out once the chrome/firefox reviews the extension.

**Comment by irsat000** [comment]
Uploaded the new version. Hopefully, it works for everyone. Check it out once chrome/firefox reviews the extension.

**Comment by irsat000** [comment]
Alright, try the new version please.

**Comment by NanaNemNem** [comment]
It works now! Thank you so much! Its greatly appreciated <3
