### ISSUE TITLE
Request[Adding Auto retry/Swiper/Try Again]

### ISSUE THREAD

**Issue by Abyss972** [irsat000/CAI-Tools#70]
Is it possible to add Auto swiper to the extension.there's a greasyfork scirpt called "Rizz your waifu" which acts as a auto swiper and displays 30+ message fastly.i think adding a function like this would make the Cai tools Much Better and easier expericne and more complete

**Comment by irsat000** [comment]
I had this in mind for a long time. But I need the bugs to be cleaned up first.

**Comment by Abyss972** [comment]
> I had this in mind for a long time. But I need the bugs to be cleaned up first.

Well then,clean up the bugs i guess.good luck on the future updates.

**Comment by irsat000** [comment]
Did you like the changes?
