### ISSUE TITLE
Summarizing "unexpected_error" issue

### ISSUE THREAD

**Issue by Sprout853** [irsat000/CAI-Tools#71]
I tried using the summarizing feature, as I had never used it before, and at first, it told me to log in chatGPT, so I did that, and I tried again, and this showed up.
![image](https://github.com/user-attachments/assets/6153be9d-8ad4-45b8-8143-c650d0016ce6)

I've tried multiple times again, and nothing's working, so I would appreciate if there's a fix to this, thanks!
(Note that I do not have ChatGPT Plus.)

**Comment by irsat000** [comment]
Yeah chatgpt is troublesome, I will get rid of it the moment I get the chance.

**Comment by irsat000** [comment]
Feature is deprecated, but I am working on a new feature that utilizes it.

**Comment by irsat000** [comment]
I found the GPT issues and solved them for the new feature. Summary feature is discontinued.
