### ISSUE TITLE
[Request] Downloading Rooms

### ISSUE THREAD

**Issue by Armel081** [irsat000/CAI-Tools#73]
So C.AI has recently announced that they're discontinuing the old site, which means all of the rooms chats will probably disappear too, and i'm wondering if you could add support for downloading rooms, preferably in the SillyTavern groupchat format, but any other format would work ifne.

**Comment by irsat000** [comment]
Duplicate https://github.com/irsat000/CAI-Tools/issues/53

**Comment by irsat000** [comment]
I might work on this, this update. Not a promise.
