### ISSUE TITLE
error cloning chat 

### ISSUE THREAD

**Issue by Jazzieboots** [irsat000/CAI-Tools#74]
Whenever trying to clone a chat, i get the error "Unexpected server error at 1/11. Unknown reason: new_candidate_raw_content is empty string for edit_turn_candidate." does anyone know how to fix it?

**Comment by irsat000** [comment]
Could you download the chat as Offline Chat and give it here? If it's safe to share of course.

It's probably only memories or it's empty spaces or something. I can fix that in the next update, I almost completed the speed boost of cloning as well.

**Comment by irsat000** [comment]
We found the problem on Reddit everyone. It will be taken care of next update.

**Comment by irsat000** [comment]
Fixed in the new version.
