### ISSUE TITLE
[Request] Export of entire history to json/jsonl

### ISSUE THREAD

**Issue by The-Shotgun** [irsat000/CAI-Tools#75]
I think it would be very nice if this extension had buttons that exports the entire chat history but in a json/jsonl formal, right now you can export a single chat to jsonl/json/html or entire history to html, but not entire history to json or jsonl. This would be useful for users who want to migrate platforms but have amassed tons of conversations on c.ai.

**Comment by irsat000** [comment]
Sorry, I want to focus on character.ai at the moment.
