### ISSUE TITLE
[Request] Download/Backup All Chats

### ISSUE THREAD

**Issue by d7c0** [irsat000/CAI-Tools#76]
Would it be feasible to implement a feature which lets you take a backup of all your chats?
Or at least "last X number of chats" or something akin to that?

**Comment by irsat000** [comment]
Offline History is right there. Click fetch and let it load. Then click tbe button.

**Comment by d7c0** [comment]
> Offline History is right there. Click fetch and let it load. Then click tbe button.

I meant for all/multiple characters.

**Comment by irsat000** [comment]
Sorry, one history already takes too long. Not a practicle approach. It won't be on the extension.

**Comment by d7c0** [comment]
> Sorry, one history already takes too long. Not a practicle approach. It won't be on the extension.

Time? My computer's got no appointments, but oh well. I gotcha

**Comment by irsat000** [comment]
I could try writing a code that will let you do that though. Should be no more than 10 lines. You paste it in the console and CAI Tools would do the rest.

I do this when I don't want to add the features in haha.

**Comment by d7c0** [comment]
> I could try writing a code that will let you do that though. You paste it in the console and CAI Tools would do the rest.
> 
> I do this when I don't want to add the features in haha. Not now though.

Sounds great. I'm just paranoid about losing chats but at the same time I'm too lazy to go in and manually backup each single one lol. If only CAI had such backups implemented themselves. But hey, they copied you when it came to duplicating pinned posts right? Maybe they'll roll the same way again

**Comment by irsat000** [comment]
If they cooied me correctly, they wouldn't put 999 message limit to duplication. That's what I heard.

**Comment by Gentokiii** [comment]
Offline history downloads all the chats for that bot? I'm a little confused on what it does, I only noticed that when it downloads a random chat, the file is much bigger than if you downloaded it normally with offline chat.

**Comment by irsat000** [comment]
Yes, the menu on top left opens the history. You can select your chats there.

**Comment by irsat000** [comment]
Sorry bro I couldn't make time for this. I have my hands full with v2.9.0 and trying to fix existing bugs.
