### ISSUE TITLE
Minor Issue: HTML exports have the same avatar image

### ISSUE THREAD

**Issue by Gentokiii** [irsat000/CAI-Tools#77]
Preface: This is a really minor issue, but I noticed about two weeks ago that whenever I export chats from my own private bot that the user's avatar is the same photo as the character's. It seems to be happening on only one bot and it started about two weeks ago or maybe a little further. 

Anyway, not a big deal, just wanted to see if I should remove the bot's photo and add it back or something. You do great work so it's no big deal if you don't have time for this. Thanks!

**Comment by irsat000** [comment]
Thank you for informing me. I will look into it.

**Comment by irsat000** [comment]
I guess I found something about it. Is your chat's first message your message? No greeting?

**Comment by Gentokiii** [comment]
No, it's not mine. But it's an edited greeting turned into a pinned message.

**Comment by Gentokiii** [comment]
Yeah just the avatars and only for select chats with that bot. The older ones are fine.

**Comment by irsat000** [comment]
Does this still happen? Btw if you have persona it will show its avatar in offline chat.

**Comment by Gentokiii** [comment]
Yeah, I have personas for all of it. It didn’t happen with a new one. 

I thought it was because I pinned the first message by the chat, but I usually do that to set the scene so I’m not sure. But yeah from what I can tell, it doesn’t happen with the new ones.

**Comment by irsat000** [comment]
Issue can stay open to confirm it never happens.

**Comment by irsat000** [comment]
I take it it was a one time thing?

**Comment by Gentokiii** [comment]
Yeah, it's not happening anymore. Not sure what happened with that one chat but the new ones I make are fine. Thanks for the help.
