### ISSUE TITLE
'signal is not defined' duplication problem

### ISSUE THREAD

**Issue by nothingonedlike** [irsat000/CAI-Tools#79]
I sorta have a problem duplicating chats, especially with the new version method. The old method works, but it is bothersome and more time consuming to remake a chat ftom scratch.

If I try to use the new method, it would say 'signal is not defined' and would proceed to 'erase clone'. This happens even after I already update the data for the conversation, and even if I try to just duplicate it to the last 500-600 messages.

![20240923_182052](https://github.com/user-attachments/assets/30c58cba-3dbd-4e66-bff7-521b86b5e482)

I tried to download the offline version of the conversation and then import it in, in hopes to circumnavigate it somehow. I also tried doing for another character and conversation, both still have the same message. 

I only just recently downloaded firefox on mobile (just to get the extension hehe) so it shouldn't be because I have to update anything. Does it have something to do with being on mobile in general? Or does it have something to do with my location?

**Comment by irsat000** [comment]
Oh my goooooodd!!!! This piece of son of a motherf, of course it would magically work on the test and will fail on production. Why wouldn't it? Because I haven't deleted this single god damn line of code when I removed the logic dependent on it.

It doesn't actually have the erase clone logic anymore actually. If you wait 10-15 minutes, you can have the clone. But please wait for me to update it again.

**Comment by irsat000** [comment]
![image](https://github.com/user-attachments/assets/c3c92f52-eba4-47dc-846a-099624f52256)

Yaaay, works again 😑😑😑

**Comment by nothingonedlike** [comment]
Thanks so much!

**Comment by irsat000** [comment]
What do you mean yet to see? Is it not working?

**Comment by nothingonedlike** [comment]
Well yeah i guess its working. I just have yet to actually duplicate a chat hehe. It's also taking pretty long since its like a five step thing. Prolly just me though always putting it in the bg
