### ISSUE TITLE
Cai tools button not appearing solved

### ISSUE THREAD

**Issue by foxtrottoolbox** [irsat000/CAI-Tools#8]
I'll be explaining how to fix the cai tools button not showing up. Thanks to @irsat000, I've figured out how to fix it. I'll show a simple tutorial on how to make the button reappear.
![Screenshot20192.jpg](https://github.com/irsat000/CAI-Tools/assets/86894250/1dae0d42-206b-4e8f-8f86-af333db57018)
First, you'll have to open a character chat. It can be any character, then edit the address bar. You'll see character.ai/chat2?. Simply remove the 2 between chat and ? and I'll look like this: character.ai/chat?. Now press enter or reload the page after editing the url adrees bar.
![Screwnshot2.jpg](https://github.com/irsat000/CAI-Tools/assets/86894250/060737e6-aeb8-4ad8-9f07-4434a535277e)
It should look like this. And patiently wait until the button loads in.
(Also, I'm using my android phone to do this)

**Comment by irsat000** [comment]
I am sorry, let me clear this up. C.AI devs made a second chat page with chat2 path in the url. It uses a different API and only your chat2 pages will appear in histories. You can't access to your chat after reload if you do this too, which means CAI Buttons showing is only good for downloading character. 

Good news and bad news.

Good news is, chat2 page problem is solved, I am fixing a few other less critical things.

Bad news is, I don't have access to this API that much, so the menu for chat2 history will not be available, unless I learn some programming magic.

More bad news, my schedule will be full until an unknown date. Excuses, excuses.

**Comment by irsat000** [comment]
New version is out. Check it out!
