### ISSUE TITLE
Error Memory Manager

### ISSUE THREAD

**Issue by CashOver** [irsat000/CAI-Tools#80]
Hi, I would like to say that the Memory Manager has been giving an error since last month, both 1v and 2v are not working. Even the "remind every messages" part isn't working.

**Comment by irsat000** [comment]
I will take a look. Does it give an error? Or not working at all without giving an error?

**Comment by CashOver** [comment]
In both Firefox and Chrome,
- Firefox version is Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
- Chrome version is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

That's what whatsmyua is saying.

**Comment by irsat000** [comment]
I tested, surprisingly this time mine is also not working. Must be a small issue that I have missed. Thankfully the v1 was loyal and working all this time.

I always assumed it was because people didn't know it wouldn't visually be shown.

**Comment by irsat000** [comment]
![image](https://github.com/user-attachments/assets/8fb0b472-4564-47cf-9a94-b9fa0d5c0c99)

LMAO, who wrote this code... oh wait, that's me :(

Basically I accidentally forgot to delete this part so it always kept throwing error for v2. And errors meet with default behavior, which is sending message normally without memories.

**Comment by CashOver** [comment]
Thank...

**Comment by irsat000** [comment]
When v2.9.0 is on the store, try it and tell me if it's solved please.

**Comment by CashOver** [comment]
It's working!
Thank again..
