### ISSUE TITLE
Accessing Old Site with CAI Tools?

### ISSUE THREAD

**Issue by JCollins2048** [irsat000/CAI-Tools#84]
Me, again.  This is more of a question than an issue or suggestion.

Is it possible, or would it be possible, to use the old / legacy website using *CAI Tools*?  Or, is that beyond the scope of the project?  I know it's still possible to get onto the old site due to how lazily they "blocked" it, but I can't figure out how, so I figured this tool suite might be one way.

Cheers and thank you!

**Comment by JCollins2048** [comment]
Actually, never mind.  This is both beyond the scope of the project and probably not feasible with the current tools.  Sorry about that.

**Comment by irsat000** [comment]
CAI Tools still support the old website under the hood but they can pull the plug any minute now.
