### ISSUE TITLE
New cloning method bug

### ISSUE THREAD

**Issue by Iexistal** [irsat000/CAI-Tools#88]
Whenever I clone, I get some of my chats replaced with messages all featuring the same memo such as "STOP, PLEASE STOP!" or "STOP REPEATING YOURSELF I WILL GIVE YOU MY HOUSE". Sometimes, the bot says earlier I sent "(this is a filler message)". What is this?

**Comment by irsat000** [comment]
It fails to modify messages for some mysterious reason. I have some test versions, do you want to try them?

**Comment by irsat000** [comment]
https://github.com/irsat000/CAI-Tools/issues/83#issuecomment-2470395395

Please try this, the issue's author is MIA

**Comment by irsat000** [comment]
Closed due to duplicate
