### ISSUE TITLE
Side Bar has vanished.

### ISSUE THREAD

**Issue by Gremblo1** [irsat000/CAI-Tools#89]
I opened Character.ai today (Kiwi browser on mobile) and usually it immediately opens the side bar that shows all the responses as they generate so they can be sent to the UI, edited and such but for some reason the tab has entirely gone.

**Comment by irsat000** [comment]
What tab? Are you perhaps using RYW (rizz your waifu) userscript?

**Comment by Gremblo1** [comment]
Ah, you are absolutely right. I'd used it so long I forgot it wasn't default to CAI tools, seems some sort of tampermonkey update has broken it. 

Thanks.

Edit: in fact it seems the script itself has broken. The creator as ceased updating it and something has finally caused it to kick the bucket.
