### ISSUE TITLE
Issue with chat history where chat persons are switched

### ISSUE THREAD

**Issue by StrictlyRomance** [irsat000/CAI-Tools#9]
![Web capture_23-7-2023_175457_beta character ai](https://github.com/irsat000/CAI-Tools/assets/140358146/14119a1b-28c1-470a-8a5a-0cd40f93d33e)
![Web capture_23-7-2023_175526_127 0 0 1](https://github.com/irsat000/CAI-Tools/assets/140358146/a7410024-3ed3-4694-89d6-fde9a4ec2c53)

Also thank you for the new fixes. You're the man!

**Comment by StrictlyRomance** [comment]
This is for a chat2 by the way. New chat after the recent chai update(chat2 and everything).

**Comment by irsat000** [comment]
Alright, I will take a look once I return home.

**Comment by irsat000** [comment]
By the way, you can drag and remove the button from the box on the left. Did you try it? I would like to hear your opinions.

**Comment by irsat000** [comment]
It should be working now.

**Comment by irsat000** [comment]
Have you tried it? I am going to close the issue if it's fixed.

**Comment by StrictlyRomance** [comment]
Yes its fixed now 👍😁. Thanks alot!

And yeah the click and drag on the button is pretty neat I guess if people want to share their screenshot and make it look cleaner. Me personally I don't mind the button being there, so I could care less.

Also the "show settings" thing is so cool. Great to take somewhat of a glimpse into the character settings of characters with hidden definitions, since you can look at the description.

![Web capture_25-7-2023_17150_127 0 0 1](https://github.com/irsat000/CAI-Tools/assets/140358146/eb5fc17d-8905-46cf-a5d8-99fee2cfb338)

![Web capture_25-7-2023_17854_beta character ai](https://github.com/irsat000/CAI-Tools/assets/140358146/27eb06f8-5518-453b-a1f7-599968e09177)

![Web capture_25-7-2023_17840_beta character ai](https://github.com/irsat000/CAI-Tools/assets/140358146/4c76104b-e117-48df-9adb-e0e32884960b)
