### ISSUE TITLE
Unable to download offline chat, character json, character card

### ISSUE THREAD

**Issue by tmscott88** [irsat000/CAI-Tools#93]
Hello, I noticed this issue with the fetch request being blocked by the CORS policy when trying to download a chat log or character details. I tried Firefox and Chrome. I can download using the Tavern chat and Ooobabooga chat fine though. Could this be a server-side block on C.AI's end?

![image](https://github.com/user-attachments/assets/d4d187e8-d024-40f7-9256-b698c0956697)

**Comment by irsat000** [comment]
This looks like a bug with the extension itself. Luckily one of the easier ones to fix, probably. Thanks for the dev tools screenshot, it will be useful.

**Comment by irsat000** [comment]
Does this still happen? I am not experiencing this with the default account from https://character.ai/ domain. Are you perhaps CAI plus member or using some other domain?

**Comment by tmscott88** [comment]
Hello, hope you're doing well. I am using a free account on the same domain you linked, though I will need to check on my own computer later. I haven't used the extension in a bit.

**Comment by tmscott88** [comment]
I just retried and the download functions worked again. Maybe their domain blocked me earlier this week for trying to download a longer chat? I think this issue is resolved for now.
