### ISSUE TITLE
not downloading but, different

### ISSUE THREAD

**Issue by Spectralwuuwu** [irsat000/CAI-Tools#96]
i get another error, but i guess is simillar said different, when i try to do a download it blocks itself
![image](https://github.com/user-attachments/assets/79820d12-2f8d-4c93-ba3a-c3a6f862d834)

now i try to create a character as i readed, i get another weird error

![image](https://github.com/user-attachments/assets/db2116f8-691c-487f-9996-695bb6dba60f)
that happens when i just click on create character

now, when i create one
[character.ai-1734561249490.log](https://github.com/user-attachments/files/18189463/character.ai-1734561249490.log)

**Comment by irsat000** [comment]
So it's a bug with the website. It's the same CORS error.

content.js is mine, the rest are the website. They suffer from the same CORS error (cross origin resource sharing). In other words, their API needs fixing. "It blocks itself" was very on point.
